### ISSUE TITLE
Failed to generate NewInClusterClient: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

### ISSUE THREAD

**Issue by nsidhaye** [asobti/kube-monkey#74]
Facing issue while running kube-monkey on our kube cluster. 

Error Log: 
```I0620 21:44:56.642406       1 config.go:74] Successfully validated configs
I0620 21:44:56.642419       1 main.go:52] Starting kube-monkey with v logging level 5 and local log directory /var/log/kube-monkey
E0620 21:44:56.643397       1 kubernetes.go:39] failed to obtain config from InClusterConfig: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
F0620 21:44:56.644008       1 main.go:55] Failed to generate NewInClusterClient: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
goroutine 1 [running]:
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.stacks(0xc42024f500, 0xc420264000, 0xa5, 0xb6)
        /go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).output(0x1785600, 0xc400000003, 0xc4200ce580, 0x1716d4a, 0x7, 0x37, 0x0)
        /go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:717 +0x30f
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).printDepth(0x1785600, 0x7f8b00000003, 0x1, 0xc42014ff48, 0x1, 0x1)
        /go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.(*loggingT).print(0x1785600, 0x3, 0xc42014ff48, 0x1, 0x1)
        /go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:637 +0x5a
github.com/asobti/kube-monkey/vendor/github.com/golang/glog.Fatal(0xc42014ff48, 0x1, 0x1)
        /go/src/github.com/asobti/kube-monkey/vendor/github.com/golang/glog/glog.go:1125 +0x53
main.main()
        /go/src/github.com/asobti/kube-monkey/main.go:55 +0x1ea
```

Not sure this is configuration related problem or something else. 

configmap.yaml

```
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: kube-system
  data:
    config.toml: |
      [kubemonkey]
      host="http://localhost:8080"
      run_hour = 8
      start_hour = 10
      end_hour = 16
      blacklisted_namespaces = ["kube-system"]
      whitelisted_namespaces = [""]
      time_zone = "America/New_York"

```

deployment.yaml
```
---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: kube-monkey
    namespace: kube-system
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: kube-monkey
      spec:
        containers:
          -  name: kube-monkey
             command:
               - "/kube-monkey"
             args: ["-v=5", "-log_dir=/var/log/kube-monkey"]
             #image: andrewsrobertamary/kube-monkey:latest
             image: kube-monkey:ubuntu
             volumeMounts:
               - name: config-volume
                 mountPath: "/etc/kube-monkey"
        volumes:
          - name: config-volume
            configMap:
              name: kube-monkey-config-map
```

We are using insecure bind address in api server. 

`KUBE_API_ADDRESS="--insecure-bind-address=0.0.0.0"`

Even I tried with adding `ServiceAccount` in KUBE_ADMISSION_CONTROL but that worsen the problem so I rollback changes. 

In our cluster `/var/run/secrets/kubernetes.io/serviceaccount/token` never created. 

We are using heapster with `--source=kubernetes:http://localhost:8080?inClusterConfig=false`

Ref: https://github.com/kubernetes/kubernetes/issues/27973

**Comment by Spellchaser** [comment]
Service account tokens are created internally by k8s. This problem is outside of kube-monkey. Verify your cluster is creating service account tokens for other pods. Do you have the Service Account Admission Controller active.

If your heapster config is using `http://localhost:8080?inClusterConfig=false` I would guess the corresponding config here should be not just be `host="http://localhost:8080"`
